Metin2RFT/Models/Entities/Item.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Metin2RFT.Models.Entities
{
    public enum ItemCategory
    {
        Kard = 1,
        Vért,
        Hátas,
        Egyéb
    }

    public class Item
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [MaxLength(70)]
        public string Name { get; set; }

        [Required]
        public ItemCategory Category { get; set; }

        public int Price { get; set; }

        [MaxLength(1000)]
        public string Description { get; set; }

        public virtual ICollection<Account> Accounts { get; set; }
    }
}

Metin2RFT/Controllers/ItemController.cs
using Metin2RFT.Models;
using Metin2RFT.Models.Entities;
using System.Linq;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace Metin2RFT.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class ItemController : Controller
    {
        // GET: /Item/Index

        [HttpGet]
        public ActionResult Index(bool? success)
        {
            using (var db = new MetinEntities())
            {
                if (success.HasValue)
                {
                    ViewBag.Message = success.Value ? "Sikeres vásárlás" : "Nincs elég egyenlege, hogy megvásárolja ezt a tárgyat. Kérjük töltse fel egyenlegét a profiljában!";
                }
                ViewBag.Balance = db.Accounts.Single(x => x.Id == WebSecurity.CurrentUserId).Balance;
                var ret = db.Items.ToList();
                return View(ret);
            }
        }

        // POST: Item/Index

        [HttpPost]
        public ActionResult Index(string sort, string search)
        {
            using (var db = new MetinEntities())
            {
                var ret = string.IsNullOrEmpty(search) ? db.Items.AsQueryable() : db.Items.Where(x => x.Name.ToLower().Contains(search.ToLower()));
                switch (sort)
                {
                    default:
                    case "Név":
                        ret = ret.OrderBy(x => x.Name);
                        break;
                    case "Ár növekvő":
                        ret = ret.OrderBy(x => x.Price);
                        break;
                    case "Ár csökkenő":
                        ret = ret.OrderByDescending(x => x.Price);
                        break;
                    case "Kategória":
                        ret = ret.OrderBy(x => x.Category);
                        break;
                }
                ViewBag.Balance = db.Accounts.Single(x => x.Id == WebSecurity.CurrentUserId).Balance;
                return View(ret.ToList());
            }
        }

        // GET: /Item/Details

        [HttpGet]
        public ActionResult Details(int id)
        {
            using (var db = new MetinEntities())
            {
                var ret = db.Items.Single(x => x.Id == id);
                ViewBag.Balance = db.Accounts.Single(x => x.Id == WebSecurity.CurrentUserId).Balance;
                return View(ret);
            }
        }

        // POST: /Item/Details

        [HttpPost]
        public ActionResult Details(Item item)
        {
            using (var db = new MetinEntities())
            {
                item = db.Items.Single(x => x.Id == item.Id);
                var user = db.Accounts.Single(x => x.Id == WebSecurity.CurrentUserId);
                var succ = true;
                if (user.Balance >= item.Price)
                {
                    user.Items.Add(item);
                    user.Balance -= item.Price;
                    db.SaveChanges();
                }
                else
                {
                    succ = false;
                }
                return RedirectToAction("Index", new { success = succ });
            }
        }
    }
}

Metin2RFT/Views/Item/Details.cshtml
@model Metin2RFT.Models.Entities.Item

@{
    ViewBag.Title = "Részletek";
}

<h2>Részletek</h2>
<h3>Jelenlegi egyenleg: @ViewBag.Balance</h3>
<div>
    <hr />
    <table>
        <tr>
            <th>
                Név
            </th>

            <th>
                Ár
            </th>

            <th>
                Leírás
            </th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>

            <td>
                @Html.DisplayFor(model => model.Price)
            </td>

            <td>
                @Html.DisplayFor(model => model.Description)
            </td>
        </tr>
    </table>
</div>

@using (Html.BeginForm("Details", "Item", FormMethod.Post))
{

    <input type="submit" value="Vásárlás" />

}

Metin2RFT/Views/Item/Index.cshtml
@model IEnumerable<Metin2RFT.Models.Entities.Item>

@{
    ViewBag.Title = "Itemshop";
}

<h2>Itemshop</h2>
@ViewBag.Message 

@using (Html.BeginForm())
{
    <h3>Jelenlegi egyenleg: @ViewBag.Balance</h3>
    /*var selectList = new SelectList(
        new List<SelectListItem>
    {
    new SelectListItem {Text = "Név", Value = "Name"},
    new SelectListItem {Text = "Ár növekvő", Value = "Price ascending"},
    new SelectListItem {Text = "Ár csökkenő", Value = "Price descending" },
    new SelectListItem {Text = "Kategória", Value = "Category"}
    }, "Value", "Text");*/
    var sorting = new string[] { "Név", "Ár növekvő", "Ár csökkenő", "Kategória" };
    @Html.DropDownList("sort", new SelectList(sorting), new { onchange = "this.form.submit();" });
    <div class="search-bar">
        @using (Html.BeginForm("Index", "Item",FormMethod.Get))
        {
        @Html.TextBox("search")
        <input type="submit" value="Keresés" class="search-button" />
        }
    </div>
    <table>
        <tr>
            <th>Kategória</th>
            <th>Tárgy neve</th>
            <th>Ára</th>
            <th>+</th>
        </tr>
        @foreach(var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(Model => item.Category)</td>
            <td>@Html.DisplayFor(Model => item.Name)</td>
            <td>@Html.DisplayFor(Model => item.Price)</td>
            <td>
               <a href='@Url.Action("Details", new {id = item.Id})'>Részletek</a>
            </td>
        </tr>
        }

    </table>

    }